// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN0yeUKUl9UIlyBO5iqM2e_yLv0sSretc',
    appId: '1:500567078083:web:93b6523267bd19a633de76',
    messagingSenderId: '500567078083',
    projectId: 'flutter-project-ac8e2',
    authDomain: 'flutter-project-ac8e2.firebaseapp.com',
    storageBucket: 'flutter-project-ac8e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkq3Z6UZ-PqcV10Qd8DZtPe0vXpfJc9A',
    appId: '1:500567078083:android:3dce43f48e5fa48333de76',
    messagingSenderId: '500567078083',
    projectId: 'flutter-project-ac8e2',
    storageBucket: 'flutter-project-ac8e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU5NQnQM7KnH3C0Y6tfZ2INmbSWlW_iuc',
    appId: '1:500567078083:ios:dec9e9c5f5af59c133de76',
    messagingSenderId: '500567078083',
    projectId: 'flutter-project-ac8e2',
    storageBucket: 'flutter-project-ac8e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU5NQnQM7KnH3C0Y6tfZ2INmbSWlW_iuc',
    appId: '1:500567078083:ios:dec9e9c5f5af59c133de76',
    messagingSenderId: '500567078083',
    projectId: 'flutter-project-ac8e2',
    storageBucket: 'flutter-project-ac8e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN0yeUKUl9UIlyBO5iqM2e_yLv0sSretc',
    appId: '1:500567078083:web:7b50f77277c414be33de76',
    messagingSenderId: '500567078083',
    projectId: 'flutter-project-ac8e2',
    authDomain: 'flutter-project-ac8e2.firebaseapp.com',
    storageBucket: 'flutter-project-ac8e2.firebasestorage.app',
  );
}
